server:
  port: 80

spring:
  profiles:
    active: dev, ncp

  #### Mysql
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${adminname}
    password: ${password}

#### mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
  configuration:
    log-impl: ${log-impl}

#### logging
logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    com.eventty.com.eventty.businessservice: ${level}

#### Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


#### SERVER BASE URL
server.base.url.user_server: ${user-server-url}
server.base.url.apply-server: ${apply-server-url}