spring:
  # Secret
  profiles:
    active: test
  # Oracle
  datasource:
    url: ${url}
    username: ${adminname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # 404 Error
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

# mybatis log - add log4jdbc.log4j2.yml and revise application-db.yml
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      sqlonly: OFF          # SQL만 로그 출력
      sqltiming: INFO       # SQL + 소요시간 출력
      audit: OFF
      resultset: OFF        # ResultSet을 포함한 모든 JDBC 호출 정보를 출력
      resultsettable: INFO  # SQL 결과 데이터 Table형식으로 출력
      connection: OFF       # 커넥션 연결/종료 정보 출력
    root: INFO
    com.evnetty.applyService: ${level}
